languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "Xwoniu"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "images/snail20250201.png"
  description = "一个强大、轻量级的 Hugo 主题。"

[params.author]
  name = "Benjamin"
  image = "images/20250201193430.png"
  headline = ""
  bio = "一个强大、轻量级的 Hugo 主题。"
  links = [
    { github = "https://github.com/benjamin603" },
    { qq = "/about/" },
    { wechat = "/about/" },
    { email = "mailto:benjamin603@qq.com" },
    { bilibili = "https://space.bilibili.com/686172177" },
    { x-twitter = "https://x.com/benjamjn603" },
    { telegram = "https://t.me/benjamin603" },
  ]