# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["笔记"]
# robots = ""

disableImageOptimization = false

defaultBackgroundImage = "/img/featured.png"
defaultFeaturedImage = "/img/annimation/4c758d7c82292f81f99d63ff1072aa9adb5c3536_raw.jpg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "/img/三叶.png" # used in: hero, and card
  showRecent = true
  showRecentItems = 12
  showMoreLink = true
  showMoreLinkDest = "tags"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = true
#  showViews = true
#  showLikes = true
  showDateUpdated = true
  showAuthor = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when layout equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editAppendPath = false
  seriesOpened = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  cardView = true
  showComments= true
  showAuthorsBadges = true
  showWordCount = false
  sharingLinks = ["bilibili", "twitter", "telegram", "email"]
  showZenMode = false

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = false
#  showViews = true
#  showLikes = true
  showTableOfContents = true
  showCards = false
  groupByYear = false
  cardView = true  #true:单张格式 false:竖向格式
  cardViewScreenWidth = false
  constrainItemsWidth = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
#  showViews = true
#  showLikes = true
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
#  showViews = true
#  showLikes = true
  showTableOfContents = true
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

#开启统计
[busuanzi]
   enable = true